increment 4
valentinaskakun/metricsService pull request #7
Opened 2022-05-16 00:15 UTC by valentinaskakun

2022-06-21 21:24 UTC, ASPecherkin requested changes
есть несколько замечаний

2022-06-21 21:24 UTC, ASPecherkin commented on cmd/agent/main.go
> +	"encoding/json"
не притично , но ститилистическое замечание - 
можно настроить goimports 
и потом бить пакеты по группам 
```go
stdlib

пакеты твоего приложения 

внешние зависимости
```
это некий стандарт читаемости, который я видел в большнистве проектов и компаний

2022-06-21 21:24 UTC, ASPecherkin commented on cmd/agent/main.go
>  	select {}
кажется остался неиспользуемый код тут

2022-06-21 21:24 UTC, ASPecherkin commented on cmd/server/main.go
> +	var SaveConfigRun config.SaveConfig
тоже ститистичкий комментарий - можно с маленькой называть переменные, но тут это не ошибка

2022-06-21 21:24 UTC, ASPecherkin commented on cmd/server/test.json
> +{"MuGauge":{},"gaugeMetric":{"Alloc":2736904,"BuckHashSys":6586,"Frees":116862,"GCCPUFraction":0.0000014851404335724984,"GCSys":2812824,"HeapAlloc":2736904,"HeapIdle":3833856,"HeapInuse":3506176,"Hea
кажется попал лишний файл в PR

2022-06-21 21:24 UTC, ASPecherkin commented on test.json
> +{"PollCount":5}
аналогично лишниый файл для PR

2022-06-21 21:24 UTC, ASPecherkin commented on internal/storage/storage.go
> +var MetricsInMem Metrics
а давай подумаем как бы тут обойтись без глобальной переменной

Кажется, что мы можем утащить её инциализацию в main и дальше всё использовать как есть 

так мы избавимся от глобальной переменной и использование станет более прозрачным и явным 

если будут вопросы - пиши

2022-06-28 10:49 UTC, valentinaskakun commented on cmd/agent/main.go
>  	select {}
кажется что здесь не лишний, но агента нужно будет переделать, в идеале использовать storage.go, который юзает сейчас сервер

2022-06-28 20:36 UTC, ASPecherkin approved these changes

2022-06-28 20:36 UTC, ASPecherkin commented on internal/handlers/handlers.go
> +				metricsRun.MuGauge.Lock()
тут скорее комметарий для читаемости - можно операцию добавления добавить как функцию поверх типа 
но это на твоё усмотрение

2022-07-03 18:14 UTC, merged